
# For Jekyll, refer the followings
#  - https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
#  - https://github.com/twbs/bootstrap/blob/v4.0.0-beta.2/_config.yml

# Social
title:              3rdstage's Wiki
description:        "Wiki of Sangmoon Oh"
authors:            "Sangmoon Oh"

markdown : kramdown
# highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
#  auto_ids:     true

encoding: utf-8
exclude:
  - .settings/
  - .git/
  - .github/
  - build/
  - js/
  - node_modules/
  - scss/
  - .project
  - Gemfile
  - README.md

plugins:
  - jekyll-toc
  - jekyll-sitemap
